//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class EmployeeData : object
    {
        
        private int CompanyIdField;
        
        private string FNameField;
        
        private int IdField;
        
        private string LNameField;
        
        private string MessageField;
        
        private int OfficeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FName
        {
            get
            {
                return this.FNameField;
            }
            set
            {
                this.FNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName
        {
            get
            {
                return this.LNameField;
            }
            set
            {
                this.LNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeId
        {
            get
            {
                return this.OfficeIdField;
            }
            set
            {
                this.OfficeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalControlOfficeData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class InternalControlOfficeData : object
    {
        
        private System.Nullable<int> AmountBudgetField;
        
        private string AmountUnitField;
        
        private int BudgetThisMonthField;
        
        private int BudgetThisYearField;
        
        private ServiceReference1.InternalControlOfficeRowData[] ControlRowsField;
        
        private bool HasEmployeeField;
        
        private bool HasVehicleBrandField;
        
        private int IdField;
        
        private ServiceReference1.InternalControlOfficeLogData[] LogsField;
        
        private string NameField;
        
        private int OfficeIdField;
        
        private int PerformedThisMonthField;
        
        private int PerformedThisYearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AmountBudget
        {
            get
            {
                return this.AmountBudgetField;
            }
            set
            {
                this.AmountBudgetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmountUnit
        {
            get
            {
                return this.AmountUnitField;
            }
            set
            {
                this.AmountUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BudgetThisMonth
        {
            get
            {
                return this.BudgetThisMonthField;
            }
            set
            {
                this.BudgetThisMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BudgetThisYear
        {
            get
            {
                return this.BudgetThisYearField;
            }
            set
            {
                this.BudgetThisYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.InternalControlOfficeRowData[] ControlRows
        {
            get
            {
                return this.ControlRowsField;
            }
            set
            {
                this.ControlRowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasEmployee
        {
            get
            {
                return this.HasEmployeeField;
            }
            set
            {
                this.HasEmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasVehicleBrand
        {
            get
            {
                return this.HasVehicleBrandField;
            }
            set
            {
                this.HasVehicleBrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.InternalControlOfficeLogData[] Logs
        {
            get
            {
                return this.LogsField;
            }
            set
            {
                this.LogsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeId
        {
            get
            {
                return this.OfficeIdField;
            }
            set
            {
                this.OfficeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerformedThisMonth
        {
            get
            {
                return this.PerformedThisMonthField;
            }
            set
            {
                this.PerformedThisMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerformedThisYear
        {
            get
            {
                return this.PerformedThisYearField;
            }
            set
            {
                this.PerformedThisYearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalControlOfficeRowData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class InternalControlOfficeRowData : object
    {
        
        private string GroupField;
        
        private int IdField;
        
        private string RowTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowText
        {
            get
            {
                return this.RowTextField;
            }
            set
            {
                this.RowTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalControlOfficeLogData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class InternalControlOfficeLogData : object
    {
        
        private string AoNrField;
        
        private System.DateTime CreatedField;
        
        private int CreatedByIdField;
        
        private System.Nullable<int> CreatedOnIdField;
        
        private bool DeletedField;
        
        private ServiceReference1.EmployeeData EmployeeField;
        
        private System.Nullable<int> IdField;
        
        private ServiceReference1.InternalControlOfficeData InternalControlOfficeField;
        
        private int InternalControlOfficeIdField;
        
        private bool IsPartSavedField;
        
        private string RegNrField;
        
        private ServiceReference1.InternalControlOfficeLogRowData[] RowsField;
        
        private ServiceReference1.VehicleBrandData VehicleBrandField;
        
        private System.Nullable<int> VehicleBrandIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AoNr
        {
            get
            {
                return this.AoNrField;
            }
            set
            {
                this.AoNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created
        {
            get
            {
                return this.CreatedField;
            }
            set
            {
                this.CreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedById
        {
            get
            {
                return this.CreatedByIdField;
            }
            set
            {
                this.CreatedByIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedOnId
        {
            get
            {
                return this.CreatedOnIdField;
            }
            set
            {
                this.CreatedOnIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.EmployeeData Employee
        {
            get
            {
                return this.EmployeeField;
            }
            set
            {
                this.EmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.InternalControlOfficeData InternalControlOffice
        {
            get
            {
                return this.InternalControlOfficeField;
            }
            set
            {
                this.InternalControlOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InternalControlOfficeId
        {
            get
            {
                return this.InternalControlOfficeIdField;
            }
            set
            {
                this.InternalControlOfficeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPartSaved
        {
            get
            {
                return this.IsPartSavedField;
            }
            set
            {
                this.IsPartSavedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNr
        {
            get
            {
                return this.RegNrField;
            }
            set
            {
                this.RegNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.InternalControlOfficeLogRowData[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.VehicleBrandData VehicleBrand
        {
            get
            {
                return this.VehicleBrandField;
            }
            set
            {
                this.VehicleBrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VehicleBrandId
        {
            get
            {
                return this.VehicleBrandIdField;
            }
            set
            {
                this.VehicleBrandIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleBrandData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class VehicleBrandData : object
    {
        
        private string CodeField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalControlOfficeLogRowData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class InternalControlOfficeLogRowData : object
    {
        
        private string CommentField;
        
        private bool DeletedField;
        
        private ServiceReference1.ICErrorCodeData[] ErrorCodesField;
        
        private string GroupField;
        
        private string HelpTextField;
        
        private System.Nullable<int> IdField;
        
        private ServiceReference1.ICOLogRowFileData[] ImageFilesField;
        
        private System.Nullable<int> InternalControlOfficeRowIdField;
        
        private bool IsEAField;
        
        private bool IsNoField;
        
        private bool IsYesField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ICErrorCodeData[] ErrorCodes
        {
            get
            {
                return this.ErrorCodesField;
            }
            set
            {
                this.ErrorCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HelpText
        {
            get
            {
                return this.HelpTextField;
            }
            set
            {
                this.HelpTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ICOLogRowFileData[] ImageFiles
        {
            get
            {
                return this.ImageFilesField;
            }
            set
            {
                this.ImageFilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InternalControlOfficeRowId
        {
            get
            {
                return this.InternalControlOfficeRowIdField;
            }
            set
            {
                this.InternalControlOfficeRowIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEA
        {
            get
            {
                return this.IsEAField;
            }
            set
            {
                this.IsEAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNo
        {
            get
            {
                return this.IsNoField;
            }
            set
            {
                this.IsNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsYes
        {
            get
            {
                return this.IsYesField;
            }
            set
            {
                this.IsYesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICErrorCodeData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class ICErrorCodeData : object
    {
        
        private string CodeField;
        
        private ServiceReference1.ICErrorCodeGroupData GroupField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ICErrorCodeGroupData Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICOLogRowFileData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class ICOLogRowFileData : object
    {
        
        private string FileNameField;
        
        private string FilePathField;
        
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICErrorCodeGroupData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class ICErrorCodeGroupData : object
    {
        
        private ServiceReference1.ICErrorCodeData[] CodesField;
        
        private int IdField;
        
        private ServiceReference1.ICErrorCodeMainGroupData MainGroupField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ICErrorCodeData[] Codes
        {
            get
            {
                return this.CodesField;
            }
            set
            {
                this.CodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ICErrorCodeMainGroupData MainGroup
        {
            get
            {
                return this.MainGroupField;
            }
            set
            {
                this.MainGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICErrorCodeMainGroupData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class ICErrorCodeMainGroupData : object
    {
        
        private ServiceReference1.ICErrorCodeGroupData[] GroupsField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ICErrorCodeGroupData[] Groups
        {
            get
            {
                return this.GroupsField;
            }
            set
            {
                this.GroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfficeData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class OfficeData : object
    {
        
        private ServiceReference1.EmployeeData[] EmployeesField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.EmployeeData[] Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarPreSalesMaintenanceData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class CarPreSalesMaintenanceData : object
    {
        
        private ServiceReference1.CarPreSaleFlowGroupData CarPreSaleFlowGroupDataField;
        
        private int IdField;
        
        private string KeyCabinetField;
        
        private int MaintenanceFormIdField;
        
        private ServiceReference1.EmployeeData MaintenanceResponsibleField;
        
        private string ParkingField;
        
        private string RegNrField;
        
        private string VehicelModelField;
        
        private int VehicleBrandIdField;
        
        private string VehicleBrandNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.CarPreSaleFlowGroupData CarPreSaleFlowGroupData
        {
            get
            {
                return this.CarPreSaleFlowGroupDataField;
            }
            set
            {
                this.CarPreSaleFlowGroupDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyCabinet
        {
            get
            {
                return this.KeyCabinetField;
            }
            set
            {
                this.KeyCabinetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaintenanceFormId
        {
            get
            {
                return this.MaintenanceFormIdField;
            }
            set
            {
                this.MaintenanceFormIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.EmployeeData MaintenanceResponsible
        {
            get
            {
                return this.MaintenanceResponsibleField;
            }
            set
            {
                this.MaintenanceResponsibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parking
        {
            get
            {
                return this.ParkingField;
            }
            set
            {
                this.ParkingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNr
        {
            get
            {
                return this.RegNrField;
            }
            set
            {
                this.RegNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicelModel
        {
            get
            {
                return this.VehicelModelField;
            }
            set
            {
                this.VehicelModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehicleBrandId
        {
            get
            {
                return this.VehicleBrandIdField;
            }
            set
            {
                this.VehicleBrandIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleBrandName
        {
            get
            {
                return this.VehicleBrandNameField;
            }
            set
            {
                this.VehicleBrandNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarPreSaleFlowGroupData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class CarPreSaleFlowGroupData : object
    {
        
        private string ColorField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarPreSalesMaintenaceBegData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class CarPreSalesMaintenaceBegData : object
    {
        
        private string BatteriCheckInfoField;
        
        private bool BatteriCheckOKField;
        
        private string BrakeCheckInfoField;
        
        private bool BrakeCheckOKField;
        
        private int CarPreSalesIdField;
        
        private string CleanCheckInfoField;
        
        private bool CleanCheckOKField;
        
        private string GearboxCheckInfoField;
        
        private bool GearboxCheckOKField;
        
        private int PerformedByIdField;
        
        private System.DateTime PerformedDateField;
        
        private string TireCheckInfoField;
        
        private bool TireCheckOKField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatteriCheckInfo
        {
            get
            {
                return this.BatteriCheckInfoField;
            }
            set
            {
                this.BatteriCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BatteriCheckOK
        {
            get
            {
                return this.BatteriCheckOKField;
            }
            set
            {
                this.BatteriCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrakeCheckInfo
        {
            get
            {
                return this.BrakeCheckInfoField;
            }
            set
            {
                this.BrakeCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BrakeCheckOK
        {
            get
            {
                return this.BrakeCheckOKField;
            }
            set
            {
                this.BrakeCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarPreSalesId
        {
            get
            {
                return this.CarPreSalesIdField;
            }
            set
            {
                this.CarPreSalesIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CleanCheckInfo
        {
            get
            {
                return this.CleanCheckInfoField;
            }
            set
            {
                this.CleanCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CleanCheckOK
        {
            get
            {
                return this.CleanCheckOKField;
            }
            set
            {
                this.CleanCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GearboxCheckInfo
        {
            get
            {
                return this.GearboxCheckInfoField;
            }
            set
            {
                this.GearboxCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GearboxCheckOK
        {
            get
            {
                return this.GearboxCheckOKField;
            }
            set
            {
                this.GearboxCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerformedById
        {
            get
            {
                return this.PerformedByIdField;
            }
            set
            {
                this.PerformedByIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PerformedDate
        {
            get
            {
                return this.PerformedDateField;
            }
            set
            {
                this.PerformedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TireCheckInfo
        {
            get
            {
                return this.TireCheckInfoField;
            }
            set
            {
                this.TireCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TireCheckOK
        {
            get
            {
                return this.TireCheckOKField;
            }
            set
            {
                this.TireCheckOKField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarPreSalesMaintenaceLagerData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class CarPreSalesMaintenaceLagerData : object
    {
        
        private string BatteriCheckInfoField;
        
        private bool BatteriCheckOKField;
        
        private string BrakeCheckInfoField;
        
        private bool BrakeCheckOKField;
        
        private int CarPreSalesIdField;
        
        private int PerformedByIdField;
        
        private System.DateTime PerformedDateField;
        
        private string TireCheckInfoField;
        
        private bool TireCheckOKField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatteriCheckInfo
        {
            get
            {
                return this.BatteriCheckInfoField;
            }
            set
            {
                this.BatteriCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BatteriCheckOK
        {
            get
            {
                return this.BatteriCheckOKField;
            }
            set
            {
                this.BatteriCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrakeCheckInfo
        {
            get
            {
                return this.BrakeCheckInfoField;
            }
            set
            {
                this.BrakeCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BrakeCheckOK
        {
            get
            {
                return this.BrakeCheckOKField;
            }
            set
            {
                this.BrakeCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarPreSalesId
        {
            get
            {
                return this.CarPreSalesIdField;
            }
            set
            {
                this.CarPreSalesIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerformedById
        {
            get
            {
                return this.PerformedByIdField;
            }
            set
            {
                this.PerformedByIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PerformedDate
        {
            get
            {
                return this.PerformedDateField;
            }
            set
            {
                this.PerformedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TireCheckInfo
        {
            get
            {
                return this.TireCheckInfoField;
            }
            set
            {
                this.TireCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TireCheckOK
        {
            get
            {
                return this.TireCheckOKField;
            }
            set
            {
                this.TireCheckOKField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarPreSalesMaintenaceStandardData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class CarPreSalesMaintenaceStandardData : object
    {
        
        private int CarPreSalesIdField;
        
        private string DocPathField;
        
        private int PerformedByIdField;
        
        private System.DateTime PerformedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarPreSalesId
        {
            get
            {
                return this.CarPreSalesIdField;
            }
            set
            {
                this.CarPreSalesIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocPath
        {
            get
            {
                return this.DocPathField;
            }
            set
            {
                this.DocPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerformedById
        {
            get
            {
                return this.PerformedByIdField;
            }
            set
            {
                this.PerformedByIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PerformedDate
        {
            get
            {
                return this.PerformedDateField;
            }
            set
            {
                this.PerformedDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QualityReportData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class QualityReportData : object
    {
        
        private System.Nullable<int> AnalysisCausedByIdField;
        
        private string AnalysisTextField;
        
        private string AoNrField;
        
        private System.DateTime CreatedField;
        
        private int CreatedByField;
        
        private int CustomerReportIdField;
        
        private bool DeletedField;
        
        private string DescriptionField;
        
        private System.Nullable<int> FinalDecisionCostField;
        
        private string FinalDecisionTextField;
        
        private int IdField;
        
        private int MyPropertyField;
        
        private int OfficeDepartmentTaskIdField;
        
        private int OfficeIdField;
        
        private System.Nullable<int> QRAnalysisHeaderIdField;
        
        private ServiceReference1.QRAttachedFileData[] QRAttachedFileDataField;
        
        private System.Nullable<int> QRFinalDecisionHeaderIdField;
        
        private int QRReportResponsibleIdField;
        
        private string RegNrField;
        
        private int ReportNrField;
        
        private string StatusField;
        
        private int StatusIdField;
        
        private System.Nullable<int> TotalCostField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AnalysisCausedById
        {
            get
            {
                return this.AnalysisCausedByIdField;
            }
            set
            {
                this.AnalysisCausedByIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnalysisText
        {
            get
            {
                return this.AnalysisTextField;
            }
            set
            {
                this.AnalysisTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AoNr
        {
            get
            {
                return this.AoNrField;
            }
            set
            {
                this.AoNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created
        {
            get
            {
                return this.CreatedField;
            }
            set
            {
                this.CreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerReportId
        {
            get
            {
                return this.CustomerReportIdField;
            }
            set
            {
                this.CustomerReportIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FinalDecisionCost
        {
            get
            {
                return this.FinalDecisionCostField;
            }
            set
            {
                this.FinalDecisionCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalDecisionText
        {
            get
            {
                return this.FinalDecisionTextField;
            }
            set
            {
                this.FinalDecisionTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyProperty
        {
            get
            {
                return this.MyPropertyField;
            }
            set
            {
                this.MyPropertyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeDepartmentTaskId
        {
            get
            {
                return this.OfficeDepartmentTaskIdField;
            }
            set
            {
                this.OfficeDepartmentTaskIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeId
        {
            get
            {
                return this.OfficeIdField;
            }
            set
            {
                this.OfficeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QRAnalysisHeaderId
        {
            get
            {
                return this.QRAnalysisHeaderIdField;
            }
            set
            {
                this.QRAnalysisHeaderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.QRAttachedFileData[] QRAttachedFileData
        {
            get
            {
                return this.QRAttachedFileDataField;
            }
            set
            {
                this.QRAttachedFileDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QRFinalDecisionHeaderId
        {
            get
            {
                return this.QRFinalDecisionHeaderIdField;
            }
            set
            {
                this.QRFinalDecisionHeaderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QRReportResponsibleId
        {
            get
            {
                return this.QRReportResponsibleIdField;
            }
            set
            {
                this.QRReportResponsibleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNr
        {
            get
            {
                return this.RegNrField;
            }
            set
            {
                this.RegNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReportNr
        {
            get
            {
                return this.ReportNrField;
            }
            set
            {
                this.ReportNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                this.StatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalCost
        {
            get
            {
                return this.TotalCostField;
            }
            set
            {
                this.TotalCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QRAttachedFileData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class QRAttachedFileData : object
    {
        
        private string FileNameField;
        
        private string FilePathField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WCFReturnResultCls", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class WCFReturnResultCls : object
    {
        
        private int IdField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginEmployee", ReplyAction="http://tempuri.org/IService1/LoginEmployeeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.EmployeeData> LoginEmployeeAsync(string username, string password, string ucid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficeInternalControls", ReplyAction="http://tempuri.org/IService1/GetOfficeInternalControlsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData[]> GetOfficeInternalControlsAsync(string username, string password, string ucid, int officeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficeInternalControl", ReplyAction="http://tempuri.org/IService1/GetOfficeInternalControlResponse")]
        System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData> GetOfficeInternalControlAsync(string username, string password, string ucid, int officeId, int officecontrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficeInternalControlLog", ReplyAction="http://tempuri.org/IService1/GetOfficeInternalControlLogResponse")]
        System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeLogData> GetOfficeInternalControlLogAsync(string username, string password, string ucid, int controlLogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficeInternalControlLogs", ReplyAction="http://tempuri.org/IService1/GetOfficeInternalControlLogsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData> GetOfficeInternalControlLogsAsync(string username, string password, string ucid, int officecontrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/InsertOfficeInternalControlPerformControlResponse")]
        System.Threading.Tasks.Task<string> InsertOfficeInternalControlPerformControlAsync(string username, string password, string ucid, ServiceReference1.InternalControlOfficeLogData officeLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOfficeInternalControlLog", ReplyAction="http://tempuri.org/IService1/UpdateOfficeInternalControlLogResponse")]
        System.Threading.Tasks.Task<string> UpdateOfficeInternalControlLogAsync(string username, string password, string ucid, ServiceReference1.InternalControlOfficeLogData officeLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/DeleteOfficeInternalControlPerformControlResponse")]
        System.Threading.Tasks.Task<string> DeleteOfficeInternalControlPerformControlAsync(string username, string password, string ucid, int logId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetICErrorCodes", ReplyAction="http://tempuri.org/IService1/GetICErrorCodesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ICErrorCodeMainGroupData[]> GetICErrorCodesAsync(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficesByCompanyId", ReplyAction="http://tempuri.org/IService1/GetOfficesByCompanyIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.OfficeData[]> GetOfficesByCompanyIdAsync(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficesAndEmployeesByCompanyId", ReplyAction="http://tempuri.org/IService1/GetOfficesAndEmployeesByCompanyIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.OfficeData[]> GetOfficesAndEmployeesByCompanyIdAsync(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCarPreSalesmaintenanceByOffice", ReplyAction="http://tempuri.org/IService1/GetCarPreSalesmaintenanceByOfficeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CarPreSalesMaintenanceData[]> GetCarPreSalesmaintenanceByOfficeAsync(string username, string password, string ucid, int officeId, System.Nullable<int> employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceBeg", ReplyAction="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceBegResponse")]
        System.Threading.Tasks.Task<string> InsertCarPreSalesmaintenanceBegAsync(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceBegData begdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceLager", ReplyAction="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceLagerResponse")]
        System.Threading.Tasks.Task<string> InsertCarPreSalesmaintenanceLagerAsync(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceLagerData lagerdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceStandard", ReplyAction="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceStandardResponse")]
        System.Threading.Tasks.Task<string> InsertCarPreSalesmaintenanceStandardAsync(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceStandardData standarddata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompanyVehicleBrands", ReplyAction="http://tempuri.org/IService1/GetCompanyVehicleBrandsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.VehicleBrandData[]> GetCompanyVehicleBrandsAsync(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertQualityReport", ReplyAction="http://tempuri.org/IService1/InsertQualityReportResponse")]
        System.Threading.Tasks.Task<ServiceReference1.WCFReturnResultCls> InsertQualityReportAsync(string username, string password, string ucid, ServiceReference1.QualityReportData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EmployeeData> LoginEmployeeAsync(string username, string password, string ucid)
        {
            return base.Channel.LoginEmployeeAsync(username, password, ucid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData[]> GetOfficeInternalControlsAsync(string username, string password, string ucid, int officeId)
        {
            return base.Channel.GetOfficeInternalControlsAsync(username, password, ucid, officeId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData> GetOfficeInternalControlAsync(string username, string password, string ucid, int officeId, int officecontrolId)
        {
            return base.Channel.GetOfficeInternalControlAsync(username, password, ucid, officeId, officecontrolId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeLogData> GetOfficeInternalControlLogAsync(string username, string password, string ucid, int controlLogId)
        {
            return base.Channel.GetOfficeInternalControlLogAsync(username, password, ucid, controlLogId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData> GetOfficeInternalControlLogsAsync(string username, string password, string ucid, int officecontrolId)
        {
            return base.Channel.GetOfficeInternalControlLogsAsync(username, password, ucid, officecontrolId);
        }
        
        public System.Threading.Tasks.Task<string> InsertOfficeInternalControlPerformControlAsync(string username, string password, string ucid, ServiceReference1.InternalControlOfficeLogData officeLog)
        {
            return base.Channel.InsertOfficeInternalControlPerformControlAsync(username, password, ucid, officeLog);
        }
        
        public System.Threading.Tasks.Task<string> UpdateOfficeInternalControlLogAsync(string username, string password, string ucid, ServiceReference1.InternalControlOfficeLogData officeLog)
        {
            return base.Channel.UpdateOfficeInternalControlLogAsync(username, password, ucid, officeLog);
        }
        
        public System.Threading.Tasks.Task<string> DeleteOfficeInternalControlPerformControlAsync(string username, string password, string ucid, int logId)
        {
            return base.Channel.DeleteOfficeInternalControlPerformControlAsync(username, password, ucid, logId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ICErrorCodeMainGroupData[]> GetICErrorCodesAsync(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetICErrorCodesAsync(username, password, ucid, companyId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.OfficeData[]> GetOfficesByCompanyIdAsync(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetOfficesByCompanyIdAsync(username, password, ucid, companyId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.OfficeData[]> GetOfficesAndEmployeesByCompanyIdAsync(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetOfficesAndEmployeesByCompanyIdAsync(username, password, ucid, companyId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CarPreSalesMaintenanceData[]> GetCarPreSalesmaintenanceByOfficeAsync(string username, string password, string ucid, int officeId, System.Nullable<int> employeeId)
        {
            return base.Channel.GetCarPreSalesmaintenanceByOfficeAsync(username, password, ucid, officeId, employeeId);
        }
        
        public System.Threading.Tasks.Task<string> InsertCarPreSalesmaintenanceBegAsync(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceBegData begdata)
        {
            return base.Channel.InsertCarPreSalesmaintenanceBegAsync(username, password, ucid, begdata);
        }
        
        public System.Threading.Tasks.Task<string> InsertCarPreSalesmaintenanceLagerAsync(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceLagerData lagerdata)
        {
            return base.Channel.InsertCarPreSalesmaintenanceLagerAsync(username, password, ucid, lagerdata);
        }
        
        public System.Threading.Tasks.Task<string> InsertCarPreSalesmaintenanceStandardAsync(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceStandardData standarddata)
        {
            return base.Channel.InsertCarPreSalesmaintenanceStandardAsync(username, password, ucid, standarddata);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.VehicleBrandData[]> GetCompanyVehicleBrandsAsync(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetCompanyVehicleBrandsAsync(username, password, ucid, companyId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WCFReturnResultCls> InsertQualityReportAsync(string username, string password, string ucid, ServiceReference1.QualityReportData data)
        {
            return base.Channel.InsertQualityReportAsync(username, password, ucid, data);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://www.bisoftextsystems.se:8080/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
