//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class EmployeeData : object
    {
        
        private int CompanyIdField;
        
        private string FNameField;
        
        private int IdField;
        
        private string LNameField;
        
        private string MessageField;
        
        private int OfficeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FName
        {
            get
            {
                return this.FNameField;
            }
            set
            {
                this.FNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName
        {
            get
            {
                return this.LNameField;
            }
            set
            {
                this.LNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeId
        {
            get
            {
                return this.OfficeIdField;
            }
            set
            {
                this.OfficeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalControlOfficeData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class InternalControlOfficeData : object
    {
        
        private System.Nullable<int> AmountBudgetField;
        
        private string AmountUnitField;
        
        private ServiceReference1.InternalControlOfficeRowData[] ControlRowsField;
        
        private bool HasEmployeeField;
        
        private bool HasVehicleBrandField;
        
        private int IdField;
        
        private string NameField;
        
        private int OfficeIdField;
        
        private int PerformedThisMonthField;
        
        private int PerformedThisYearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AmountBudget
        {
            get
            {
                return this.AmountBudgetField;
            }
            set
            {
                this.AmountBudgetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmountUnit
        {
            get
            {
                return this.AmountUnitField;
            }
            set
            {
                this.AmountUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.InternalControlOfficeRowData[] ControlRows
        {
            get
            {
                return this.ControlRowsField;
            }
            set
            {
                this.ControlRowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasEmployee
        {
            get
            {
                return this.HasEmployeeField;
            }
            set
            {
                this.HasEmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasVehicleBrand
        {
            get
            {
                return this.HasVehicleBrandField;
            }
            set
            {
                this.HasVehicleBrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeId
        {
            get
            {
                return this.OfficeIdField;
            }
            set
            {
                this.OfficeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerformedThisMonth
        {
            get
            {
                return this.PerformedThisMonthField;
            }
            set
            {
                this.PerformedThisMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerformedThisYear
        {
            get
            {
                return this.PerformedThisYearField;
            }
            set
            {
                this.PerformedThisYearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalControlOfficeRowData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class InternalControlOfficeRowData : object
    {
        
        private string GroupField;
        
        private int IdField;
        
        private string RowTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowText
        {
            get
            {
                return this.RowTextField;
            }
            set
            {
                this.RowTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalControlOfficeLogData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class InternalControlOfficeLogData : object
    {
        
        private string AoNrField;
        
        private System.DateTime CreatedField;
        
        private int CreatedByIdField;
        
        private System.Nullable<int> CreatedOnIdField;
        
        private bool DeletedField;
        
        private System.Nullable<int> IdField;
        
        private int InternalControlOfficeIdField;
        
        private bool IsPartSavedField;
        
        private string RegNrField;
        
        private ServiceReference1.InternalControlOfficeLogRowData[] RowsField;
        
        private System.Nullable<int> VehicleBrandIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AoNr
        {
            get
            {
                return this.AoNrField;
            }
            set
            {
                this.AoNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created
        {
            get
            {
                return this.CreatedField;
            }
            set
            {
                this.CreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedById
        {
            get
            {
                return this.CreatedByIdField;
            }
            set
            {
                this.CreatedByIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedOnId
        {
            get
            {
                return this.CreatedOnIdField;
            }
            set
            {
                this.CreatedOnIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InternalControlOfficeId
        {
            get
            {
                return this.InternalControlOfficeIdField;
            }
            set
            {
                this.InternalControlOfficeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPartSaved
        {
            get
            {
                return this.IsPartSavedField;
            }
            set
            {
                this.IsPartSavedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNr
        {
            get
            {
                return this.RegNrField;
            }
            set
            {
                this.RegNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.InternalControlOfficeLogRowData[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VehicleBrandId
        {
            get
            {
                return this.VehicleBrandIdField;
            }
            set
            {
                this.VehicleBrandIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalControlOfficeLogRowData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class InternalControlOfficeLogRowData : object
    {
        
        private string CommentField;
        
        private bool DeletedField;
        
        private System.Nullable<int> IdField;
        
        private int InternalControlOfficeLogRowIdField;
        
        private bool IsEAField;
        
        private bool IsNoField;
        
        private bool IsYesField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InternalControlOfficeLogRowId
        {
            get
            {
                return this.InternalControlOfficeLogRowIdField;
            }
            set
            {
                this.InternalControlOfficeLogRowIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEA
        {
            get
            {
                return this.IsEAField;
            }
            set
            {
                this.IsEAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNo
        {
            get
            {
                return this.IsNoField;
            }
            set
            {
                this.IsNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsYes
        {
            get
            {
                return this.IsYesField;
            }
            set
            {
                this.IsYesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICErrorCodeMainGroupData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class ICErrorCodeMainGroupData : object
    {
        
        private ServiceReference1.ICErrorCodeGroupData[] GroupsField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ICErrorCodeGroupData[] Groups
        {
            get
            {
                return this.GroupsField;
            }
            set
            {
                this.GroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICErrorCodeGroupData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class ICErrorCodeGroupData : object
    {
        
        private ServiceReference1.ICErrorCodeData[] CodesField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ICErrorCodeData[] Codes
        {
            get
            {
                return this.CodesField;
            }
            set
            {
                this.CodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICErrorCodeData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class ICErrorCodeData : object
    {
        
        private string CodeField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfficeData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class OfficeData : object
    {
        
        private ServiceReference1.EmployeeData[] EmployeesField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.EmployeeData[] Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarPreSalesMaintenanceData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class CarPreSalesMaintenanceData : object
    {
        
        private ServiceReference1.CarPreSaleFlowGroupData CarPreSaleFlowGroupDataField;
        
        private int IdField;
        
        private string KeyCabinetField;
        
        private ServiceReference1.EmployeeData MaintenanceResponsibleField;
        
        private string ParkingField;
        
        private string RegNrField;
        
        private string VehicelModelField;
        
        private int VehicleBrandIdField;
        
        private string VehicleBrandNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.CarPreSaleFlowGroupData CarPreSaleFlowGroupData
        {
            get
            {
                return this.CarPreSaleFlowGroupDataField;
            }
            set
            {
                this.CarPreSaleFlowGroupDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyCabinet
        {
            get
            {
                return this.KeyCabinetField;
            }
            set
            {
                this.KeyCabinetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.EmployeeData MaintenanceResponsible
        {
            get
            {
                return this.MaintenanceResponsibleField;
            }
            set
            {
                this.MaintenanceResponsibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parking
        {
            get
            {
                return this.ParkingField;
            }
            set
            {
                this.ParkingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNr
        {
            get
            {
                return this.RegNrField;
            }
            set
            {
                this.RegNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicelModel
        {
            get
            {
                return this.VehicelModelField;
            }
            set
            {
                this.VehicelModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehicleBrandId
        {
            get
            {
                return this.VehicleBrandIdField;
            }
            set
            {
                this.VehicleBrandIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleBrandName
        {
            get
            {
                return this.VehicleBrandNameField;
            }
            set
            {
                this.VehicleBrandNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarPreSaleFlowGroupData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class CarPreSaleFlowGroupData : object
    {
        
        private string ColorField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarPreSalesMaintenaceBegData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class CarPreSalesMaintenaceBegData : object
    {
        
        private string BatteriCheckInfoField;
        
        private bool BatteriCheckOKField;
        
        private string BrakeCheckInfoField;
        
        private bool BrakeCheckOKField;
        
        private int CarPreSalesIdField;
        
        private string CleanCheckInfoField;
        
        private bool CleanCheckOKField;
        
        private string GearboxCheckInfoField;
        
        private bool GearboxCheckOKField;
        
        private int PerformedByIdField;
        
        private System.DateTime PerformedDateField;
        
        private string TireCheckInfoField;
        
        private bool TireCheckOKField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatteriCheckInfo
        {
            get
            {
                return this.BatteriCheckInfoField;
            }
            set
            {
                this.BatteriCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BatteriCheckOK
        {
            get
            {
                return this.BatteriCheckOKField;
            }
            set
            {
                this.BatteriCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrakeCheckInfo
        {
            get
            {
                return this.BrakeCheckInfoField;
            }
            set
            {
                this.BrakeCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BrakeCheckOK
        {
            get
            {
                return this.BrakeCheckOKField;
            }
            set
            {
                this.BrakeCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarPreSalesId
        {
            get
            {
                return this.CarPreSalesIdField;
            }
            set
            {
                this.CarPreSalesIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CleanCheckInfo
        {
            get
            {
                return this.CleanCheckInfoField;
            }
            set
            {
                this.CleanCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CleanCheckOK
        {
            get
            {
                return this.CleanCheckOKField;
            }
            set
            {
                this.CleanCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GearboxCheckInfo
        {
            get
            {
                return this.GearboxCheckInfoField;
            }
            set
            {
                this.GearboxCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GearboxCheckOK
        {
            get
            {
                return this.GearboxCheckOKField;
            }
            set
            {
                this.GearboxCheckOKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerformedById
        {
            get
            {
                return this.PerformedByIdField;
            }
            set
            {
                this.PerformedByIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PerformedDate
        {
            get
            {
                return this.PerformedDateField;
            }
            set
            {
                this.PerformedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TireCheckInfo
        {
            get
            {
                return this.TireCheckInfoField;
            }
            set
            {
                this.TireCheckInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TireCheckOK
        {
            get
            {
                return this.TireCheckOKField;
            }
            set
            {
                this.TireCheckOKField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleBrandData", Namespace="http://schemas.datacontract.org/2004/07/BisoftMobileWCFService.Classes")]
    public partial class VehicleBrandData : object
    {
        
        private string CodeField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginEmployee", ReplyAction="http://tempuri.org/IService1/LoginEmployeeResponse")]
        ServiceReference1.EmployeeData LoginEmployee(string username, string password, string ucid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginEmployee", ReplyAction="http://tempuri.org/IService1/LoginEmployeeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.EmployeeData> LoginEmployeeAsync(string username, string password, string ucid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficeInternalControls", ReplyAction="http://tempuri.org/IService1/GetOfficeInternalControlsResponse")]
        ServiceReference1.InternalControlOfficeData[] GetOfficeInternalControls(string username, string password, string ucid, int officeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficeInternalControls", ReplyAction="http://tempuri.org/IService1/GetOfficeInternalControlsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData[]> GetOfficeInternalControlsAsync(string username, string password, string ucid, int officeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/GetOfficeInternalControlPerformControlResponse")]
        ServiceReference1.InternalControlOfficeData GetOfficeInternalControlPerformControl(string username, string password, string ucid, int officeId, int officecontrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/GetOfficeInternalControlPerformControlResponse")]
        System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData> GetOfficeInternalControlPerformControlAsync(string username, string password, string ucid, int officeId, int officecontrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/InsertOfficeInternalControlPerformControlResponse")]
        string InsertOfficeInternalControlPerformControl(ServiceReference1.InternalControlOfficeLogData officeLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/InsertOfficeInternalControlPerformControlResponse")]
        System.Threading.Tasks.Task<string> InsertOfficeInternalControlPerformControlAsync(ServiceReference1.InternalControlOfficeLogData officeLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/UpdateOfficeInternalControlPerformControlResponse")]
        string UpdateOfficeInternalControlPerformControl(ServiceReference1.InternalControlOfficeLogData officeLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/UpdateOfficeInternalControlPerformControlResponse")]
        System.Threading.Tasks.Task<string> UpdateOfficeInternalControlPerformControlAsync(ServiceReference1.InternalControlOfficeLogData officeLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/DeleteOfficeInternalControlPerformControlResponse")]
        string DeleteOfficeInternalControlPerformControl(int logId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOfficeInternalControlPerformControl", ReplyAction="http://tempuri.org/IService1/DeleteOfficeInternalControlPerformControlResponse")]
        System.Threading.Tasks.Task<string> DeleteOfficeInternalControlPerformControlAsync(int logId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetICErrorCodes", ReplyAction="http://tempuri.org/IService1/GetICErrorCodesResponse")]
        ServiceReference1.ICErrorCodeMainGroupData[] GetICErrorCodes(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetICErrorCodes", ReplyAction="http://tempuri.org/IService1/GetICErrorCodesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ICErrorCodeMainGroupData[]> GetICErrorCodesAsync(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficesByCompanyId", ReplyAction="http://tempuri.org/IService1/GetOfficesByCompanyIdResponse")]
        ServiceReference1.OfficeData[] GetOfficesByCompanyId(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficesByCompanyId", ReplyAction="http://tempuri.org/IService1/GetOfficesByCompanyIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.OfficeData[]> GetOfficesByCompanyIdAsync(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficesAndEmployeesByCompanyId", ReplyAction="http://tempuri.org/IService1/GetOfficesAndEmployeesByCompanyIdResponse")]
        ServiceReference1.OfficeData[] GetOfficesAndEmployeesByCompanyId(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOfficesAndEmployeesByCompanyId", ReplyAction="http://tempuri.org/IService1/GetOfficesAndEmployeesByCompanyIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.OfficeData[]> GetOfficesAndEmployeesByCompanyIdAsync(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCarPreSalesmaintenanceByOffice", ReplyAction="http://tempuri.org/IService1/GetCarPreSalesmaintenanceByOfficeResponse")]
        ServiceReference1.CarPreSalesMaintenanceData[] GetCarPreSalesmaintenanceByOffice(string username, string password, string ucid, int officeId, System.Nullable<int> employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCarPreSalesmaintenanceByOffice", ReplyAction="http://tempuri.org/IService1/GetCarPreSalesmaintenanceByOfficeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CarPreSalesMaintenanceData[]> GetCarPreSalesmaintenanceByOfficeAsync(string username, string password, string ucid, int officeId, System.Nullable<int> employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceBeg", ReplyAction="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceBegResponse")]
        string InsertCarPreSalesmaintenanceBeg(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceBegData begdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceBeg", ReplyAction="http://tempuri.org/IService1/InsertCarPreSalesmaintenanceBegResponse")]
        System.Threading.Tasks.Task<string> InsertCarPreSalesmaintenanceBegAsync(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceBegData begdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompanyVehicleBrands", ReplyAction="http://tempuri.org/IService1/GetCompanyVehicleBrandsResponse")]
        ServiceReference1.VehicleBrandData[] GetCompanyVehicleBrands(string username, string password, string ucid, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompanyVehicleBrands", ReplyAction="http://tempuri.org/IService1/GetCompanyVehicleBrandsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.VehicleBrandData[]> GetCompanyVehicleBrandsAsync(string username, string password, string ucid, int companyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.EmployeeData LoginEmployee(string username, string password, string ucid)
        {
            return base.Channel.LoginEmployee(username, password, ucid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EmployeeData> LoginEmployeeAsync(string username, string password, string ucid)
        {
            return base.Channel.LoginEmployeeAsync(username, password, ucid);
        }
        
        public ServiceReference1.InternalControlOfficeData[] GetOfficeInternalControls(string username, string password, string ucid, int officeId)
        {
            return base.Channel.GetOfficeInternalControls(username, password, ucid, officeId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData[]> GetOfficeInternalControlsAsync(string username, string password, string ucid, int officeId)
        {
            return base.Channel.GetOfficeInternalControlsAsync(username, password, ucid, officeId);
        }
        
        public ServiceReference1.InternalControlOfficeData GetOfficeInternalControlPerformControl(string username, string password, string ucid, int officeId, int officecontrolId)
        {
            return base.Channel.GetOfficeInternalControlPerformControl(username, password, ucid, officeId, officecontrolId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InternalControlOfficeData> GetOfficeInternalControlPerformControlAsync(string username, string password, string ucid, int officeId, int officecontrolId)
        {
            return base.Channel.GetOfficeInternalControlPerformControlAsync(username, password, ucid, officeId, officecontrolId);
        }
        
        public string InsertOfficeInternalControlPerformControl(ServiceReference1.InternalControlOfficeLogData officeLog)
        {
            return base.Channel.InsertOfficeInternalControlPerformControl(officeLog);
        }
        
        public System.Threading.Tasks.Task<string> InsertOfficeInternalControlPerformControlAsync(ServiceReference1.InternalControlOfficeLogData officeLog)
        {
            return base.Channel.InsertOfficeInternalControlPerformControlAsync(officeLog);
        }
        
        public string UpdateOfficeInternalControlPerformControl(ServiceReference1.InternalControlOfficeLogData officeLog)
        {
            return base.Channel.UpdateOfficeInternalControlPerformControl(officeLog);
        }
        
        public System.Threading.Tasks.Task<string> UpdateOfficeInternalControlPerformControlAsync(ServiceReference1.InternalControlOfficeLogData officeLog)
        {
            return base.Channel.UpdateOfficeInternalControlPerformControlAsync(officeLog);
        }
        
        public string DeleteOfficeInternalControlPerformControl(int logId)
        {
            return base.Channel.DeleteOfficeInternalControlPerformControl(logId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteOfficeInternalControlPerformControlAsync(int logId)
        {
            return base.Channel.DeleteOfficeInternalControlPerformControlAsync(logId);
        }
        
        public ServiceReference1.ICErrorCodeMainGroupData[] GetICErrorCodes(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetICErrorCodes(username, password, ucid, companyId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ICErrorCodeMainGroupData[]> GetICErrorCodesAsync(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetICErrorCodesAsync(username, password, ucid, companyId);
        }
        
        public ServiceReference1.OfficeData[] GetOfficesByCompanyId(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetOfficesByCompanyId(username, password, ucid, companyId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.OfficeData[]> GetOfficesByCompanyIdAsync(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetOfficesByCompanyIdAsync(username, password, ucid, companyId);
        }
        
        public ServiceReference1.OfficeData[] GetOfficesAndEmployeesByCompanyId(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetOfficesAndEmployeesByCompanyId(username, password, ucid, companyId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.OfficeData[]> GetOfficesAndEmployeesByCompanyIdAsync(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetOfficesAndEmployeesByCompanyIdAsync(username, password, ucid, companyId);
        }
        
        public ServiceReference1.CarPreSalesMaintenanceData[] GetCarPreSalesmaintenanceByOffice(string username, string password, string ucid, int officeId, System.Nullable<int> employeeId)
        {
            return base.Channel.GetCarPreSalesmaintenanceByOffice(username, password, ucid, officeId, employeeId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CarPreSalesMaintenanceData[]> GetCarPreSalesmaintenanceByOfficeAsync(string username, string password, string ucid, int officeId, System.Nullable<int> employeeId)
        {
            return base.Channel.GetCarPreSalesmaintenanceByOfficeAsync(username, password, ucid, officeId, employeeId);
        }
        
        public string InsertCarPreSalesmaintenanceBeg(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceBegData begdata)
        {
            return base.Channel.InsertCarPreSalesmaintenanceBeg(username, password, ucid, begdata);
        }
        
        public System.Threading.Tasks.Task<string> InsertCarPreSalesmaintenanceBegAsync(string username, string password, string ucid, ServiceReference1.CarPreSalesMaintenaceBegData begdata)
        {
            return base.Channel.InsertCarPreSalesmaintenanceBegAsync(username, password, ucid, begdata);
        }
        
        public ServiceReference1.VehicleBrandData[] GetCompanyVehicleBrands(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetCompanyVehicleBrands(username, password, ucid, companyId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.VehicleBrandData[]> GetCompanyVehicleBrandsAsync(string username, string password, string ucid, int companyId)
        {
            return base.Channel.GetCompanyVehicleBrandsAsync(username, password, ucid, companyId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://www.bisoftextsystems.se:8080/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
